name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox lint
        run: tox -e lint

      - name: Fail if git state is dirty after lint
        run: |
          if ! git diff --quiet || ! git diff --cached --quiet; then
            echo "ERROR: Linting produced changes. Please commit them."
            git status
            git --no-pager diff
            exit 1
          fi
